ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"

default_platform(:ios)

platform :ios do
  desc "Create and unlock keychain"
  lane :setup do
    create_keychain(
      name: "temp_keychain",
      password: ENV["KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600, # The keychain will be unlocked for this duration
      lock_when_sleeps: true
    )
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      is_key_content_base64: true,
      in_house: false  # set to true if you're part of the Apple Enterprise Program
    )
    match(
      type: "appstore",
      platform: "ios",
      # readonly: true,
      keychain_name: "temp_keychain", # Specify the keychain name
      keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )
  end

  desc "Deploy a new version for internal testing"
  lane :dev_ios do
    scan(
      device: ENV['SIMULATOR_ID']
    )
    gym(
      scheme: "Cornerstones",
      export_options: {
        provisioningProfiles: {
          "co.lookscope.cornerstones": "match AppStore co.lookscope.cornerstones"
        },
        signingStyle: "manual",
        method: "app-store"
      }
    )
    pilot(
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
    increment_build_number
    delete_keychain(name: "temp_keychain")
  end
end
