name: Run tests

on:
  push

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create and boot simulator
      run: |
        SIMULATOR_ID=$(xcrun simctl create "NewSimulator" "iPhone 15" iOS 17.0)
        xcrun simctl boot "$SIMULATOR_ID"
        echo "SIMULATOR_ID=$SIMULATOR_ID" >> $GITHUB_ENV

    - name: Install fastlane
      run: |
        bundle install

    - name: Execute fastlane
      run: |
        bundle exec fastlane dev_ios
      env:
        SIMULATOR_ID: ${{ env.SIMULATOR_ID }}
