name: Run tests

on:
  push

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: List available simulators
      run: xcrun simctl list devicetypes runtimes

    - name: Create and boot simulator
      run: |
        SIMULATOR_ID=$(xcrun simctl create "NewSimulator" "iPhone 14" "com.apple.CoreSimulator.SimRuntime.iOS-16-2")
        xcrun simctl boot "$SIMULATOR_ID"
        echo "SIMULATOR_ID=$SIMULATOR_ID" >> $GITHUB_ENV

    - name: Configure Git to use PAT
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.email "json@lookscopeapp.com"
        git config --global user.name "Jay's CI Bot"
        git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n json@lookscopeapp.com:${GH_PERSONAL_ACCESS_TOKEN} | base64)"

    - name: Install fastlane
      run: |
        bundle install

    - name: Execute fastlane
      run: |
        bundle exec fastlane dev_ios
      env:
        SIMULATOR_ID: ${{ env.SIMULATOR_ID }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
