name: Run tests

on:
  push

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: List available simulators
      run: xcrun simctl list devicetypes runtimes

    - name: Create and boot simulator
      run: |
        SIMULATOR_ID=$(xcrun simctl create "NewSimulator" "iPhone 14" "com.apple.CoreSimulator.SimRuntime.iOS-16-2")
        xcrun simctl boot "$SIMULATOR_ID"
        echo "SIMULATOR_ID=$SIMULATOR_ID" >> $GITHUB_ENV

    - name: Clone certificates repo
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      run: |
        git clone https://x-access-token:${GH_PAT}@github.com/lookscope/cornerstones-fastlane-match.git

    - name: Install fastlane
      run: |
        bundle install

    - name: Execute fastlane
      run: |
        bundle exec fastlane dev_ios
      env:
        SIMULATOR_ID: ${{ env.SIMULATOR_ID }}
